### ISSUE TITLE
the features page not found

### ISSUE THREAD

**Issue by ohmycloud** [Raku/features#9]
http://perl6.org/compilers/features page not found when clicked. And it referenced by https://docs.perl6.org/language/faq

**Comment by AlexDaniel** [comment]
Ping @rba.

**Comment by lizmat** [comment]
Without any other active Raku compiler development, it seems rather pointless to be emphasising that with a specific page.  I would therefore suggest we close this issue and archive this repo.

**Comment by JJ** [comment]
Please do the honors.
